import Navbar from "@/components/navbar/navbar";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Task Manager | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
