
import AuthProtectedRoutes from "@/HOC/auth-protected-route";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Task Manager | Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <AuthProtectedRoutes>
      {children}
    </AuthProtectedRoutes>
    </>
  );
}
